name: My first custom workflow

on:
  pull_request:
    branches: [ master ]
  
jobs:

  First-build_job:
  
    runs-on: macos-latest

    steps:

      - name: Greet me
        run: echo 'Hello Abrar, Happy learning!'; date
        
      - name: Find out Mac  Os version
        run: uname -a; date
        
      - name: Check disk utilization
        run: df -h; date
      
      
      

