name: My first custom workflow

on:
  push:
    branches: [ master ]
  
jobs:

  First-build_job:
  
    runs-on: macos-latest

    steps:

      - name: Greet me
        run: echo 'Hello Abrar, Happy learning!'

